### ISSUE TITLE
koji does not respect config in `~/.config/koji/config.toml`

### ISSUE THREAD

**Issue by untcha** [cococonscious/koji#118]
**Describe the bug**
I created a `config.toml` in `~/.config/koji/` with only one config line: `emoji = true`
When I run just `koji` in a git repository it does not show emojis.
When I run `koji --config ~/.config/koji/config.toml` the emojis are shown.

**To Reproduce**
See `Describe the bug` above

**Expected behavior**
`koji` is respecting the config in `$XDG_CONFIG_HOME/koji/config.toml`

**Screenshots**
<img width="1003" alt="image" src="https://github.com/user-attachments/assets/9b8acff4-f8e9-4eea-8de5-baa414730f54" />

**Additional context**
OS: macOS with zsh
Terminal: Alacritty with tmux; iTerm2 (both tested)

Putting a `.koji.toml` in the git repository works fine!

**Comment by cococonscious** [comment]
Hi Alexander, thanks for your great bug report! I'm working on a fix.

**Comment by cococonscious** [comment]
The issue should now be fixed on the main branch, so either install koji directly from the repository (`cargo install --git https://github.com/cococonscious/koji`) or wait for the next release (PR #117).

**Comment by cococonscious** [comment]
It should now be working with v3.1.0, feel free to reopen the issue if the problem persists.
