### ISSUE TITLE
koji --hook does not handle the message from `git commit -m "msg"`

### ISSUE THREAD

**Issue by coolaj86** [cococonscious/koji#47]
**Describe the bug**

I've got koji set up as a git hook:

`.git/modules/installers/hooks/prepare-commit-msg`
```bash
#!/bin/bash
koji --hook
```

When I run `git commit -m "some description"`, it does not use the description that I gave:

```txt
app@beta ~/project> git commit -m "blah blah blah"
✔ What type of change are you committing? · feat
✔ What is the scope of this change? (press enter to skip) ·
? Write a short, imperative tense description of the change. ›
```

**Expected behavior**

When I run `git commit -m "some description"`, koji should pre-populate the message with `some description`.

Ideally, I would like to be able to use `git commit -m "feature(thing): something nice"` or `git commit -m "doc: more words"`  and koji suggest a fix for my spelling mistake, such as `feat` or `docs`.

**Comment by coolaj86** [comment]
I think it should read in the file defined by `COMMIT_EDITMSG` to get the message that was passed via `git commit -m`.

**Comment by its-danny** [comment]
this is a good idea. it could work so that if your message fits the conventional commit standard, it's used in place of the interactive prompt. if it's not, it's used as the message during the prompt.

fixing spelling mistakes seems easy enough too, i think.
