### ISSUE TITLE
type to select

### ISSUE THREAD

**Issue by coolaj86** [cococonscious/koji#48]
**Is your feature request related to a problem? Please describe.**

Currently when I use koji my only option to select text is to use the arrow keys. 😢

**Describe the solution you'd like**

If I start typing, let's say `f`, then `feat` should be selected. Or if I type `d`, then `docs` should be selected.

**Comment by its-danny** [comment]
i also wanted this, but i'd need to open a PR to [requestty](https://crates.io/crates/requestty) to support it. i'll keep this PR open but might be a while before it gets closed since not sure when i'll have time to dive into their code base and figure out how to add this.

**Comment by cococonscious** [comment]
[inquire](https://crates.io/crates/inquire) supports this with their `Select` prompt and seems to be much more popular and active than requestty, so it might be worth migrating to it. I will look into it in the next few weeks.
