### ISSUE TITLE
windows version missing

### ISSUE THREAD

**Issue by rexlManu** [cococonscious/koji#52]
Hey,

I had 1.2.0 installed and there was a windows version but after that version you changed the publish process and you don't built windows anymore.

Is there a limitation or something like that, why you don't provide it anymore.

**Comment by its-danny** [comment]
I just haven't had time to get it set up. I think it previously worked when I was using a different setup [here](https://github.com/its-danny/koji/blob/main/.github/workflows/publish.yml). I'll try to get it working over the weekend, I just have no real experience with GitHub actions so its a bit of trial and error.
