### ISSUE TITLE
Koji does not work on M1 MacBook Pro with macOS v12.3 (21E230)

### ISSUE THREAD

**Issue by Kiran-B** [cococonscious/koji#53]
**Describe the bug**
The koji tool fails to run on the latest macOS. This is possibly due to dependency on OpenSSLv3.

**To Reproduce**
Install Koji using the following command in the terminal:
curl -sS https://webinstall.dev/koji | bash
Run koji:
koji

This problem occurs even if the release is directly downloaded from Github release page.

**Expected behavior**
Koji should run

**Screenshots**
dyld[54780]: Library not loaded: /usr/local/opt/openssl@3/lib/libssl.3.dylib
  Referenced from: ~/.local/opt/koji-v1.4.0/bin/koji
  Reason: tried: '/usr/local/opt/openssl@3/lib/libssl.3.dylib' (no such file), '/usr/local/lib/libssl.3.dylib' (no such file), '/usr/lib/libssl.3.dylib' (no such file)
[1]    54780 abort      koji

**Additional context**
On macOS `openssl version` yields the following:
LibreSSL 2.8.3

**Comment by Kiran-B** [comment]
Missed possibly an important detail when reporting this bug. 
This failure is observed on an M1 Macbook Pro. So updated the title accordingly.

For any fellow Mac users on the same boat, the following workaround makes Koji work on an M1 based macOS:
1. You would need a copy of `OpenSSL 3` in `x86_64` architecture. One of the ways to get this is via Homebrew. Note that Homebrew installs ARM64 version of OpenSSL. To force Homebrew to install an x86_64 version, I followed this guide: https://medium.com/mkdir-awesome/how-to-install-x86-64-homebrew-packages-on-apple-m1-macbook-54ba295230f

2.  Assuming you followed above guide, you may get x86_64 version of OpenSSL using the following command: `axbrew install openssl@3`

3. Above step would install OpenSSL in the following path: `/usr/local/homebrew/Cellar/openssl@3`

4. Koji expects  OpenSSL to be in the path `/usr/local/opt/openssl@3/lib/libssl.3.dylib`. Hence use `ln` command to create an alias: `sudo ln -s /usr/local/homebrew/Cellar/openssl@3/3.0.2 /usr/local/opt/openssl@3`

5. Run `Koji` in your terminal. 🎉

**Comment by Kiran-B** [comment]
Another takeaway is probably that the macOS binary of Koji is `x86_64`. I could confirm using the file command:
```
❯ file ~/.local/bin/Koji
~/.local/bin/Koji: Mach-O 64-bit executable x86_64
```
Offering Koji binary in `arm64` architecture might simplify the steps required to install OpenSSL or solve this issue altogether.

**Comment by its-danny** [comment]
@Kiran-B Sorry for super late response, been busy switching jobs and all that. Much appreciated documenting all this.

For now, I'm just going to put a link in the README to your [comment](https://github.com/its-danny/koji/issues/53#issuecomment-1076690486) on getting x86_64 OpenSSL installed. At some point I'll try and get this working, but as it is I have no real way to test any of it and it seems like getting it to build for arm64 is not that easy (or, at least, is beyond me).
