### ISSUE TITLE
Cannot run on macOS

### ISSUE THREAD

**Issue by mjablecnik** [cococonscious/koji#81]
Hello, I downloaded and want to try your tool on my macBook Air but I cannot run it:
![Screenshot 2023-11-28 at 17 25 09](https://github.com/its-danny/koji/assets/2686906/7f4dacdd-01d5-4dcd-84ba-de1b7d1c686a)

**Comment by its-danny** [comment]
heyo, @mjablecnik. you need to go to `Settings -> Privacy & Security` and let OS X know it's ok to run it. that should do it.

**Comment by mjablecnik** [comment]
@its-danny Thank you for your response. Finally I installed it via your webinstall bash script.
So now I can close this issue.. :)
