### ISSUE TITLE
Error with cocogitto git-hooks

### ISSUE THREAD

**Issue by Aparaxium** [cococonscious/koji#82]
**Describe the bug**
Running Koji with a hook installed by cocogitto results in the error:

```
Error: failed to parse config cause unknown field 'git_hooks', expected one of 'from_latest_tag', 'ignore_merge_commits', 'monorepo_version_separator', 'branch_whitelist', 'tag_prefix', 'pre_bump_hooks', 'post_bump_hooks', 'pre_package_bump_hooks', 'post_package_bump_hooks', 'commit_types', 'changelog', 'bump_profiles', 'packages'
```

**To Reproduce**
create a cog.toml with the following content:
```
[git_hooks.commit-msg]
script = """#!/bin/bash

set -e

cog verify --file ${1}
"""
```

run 
```cog install-hook --all```

in the same repo run koji

**Expected behavior**
koji commits the message and cog verify passes.

**Additional context**
I have no idea if this is a cocogitto issue or a koji issue. Committing without koji works fine.

**Comment by Aparaxium** [comment]
After some more testing it looks like the error is being caused by the cog.toml file itself. Perhaps a complete cog.toml is required?

**Comment by Aparaxium** [comment]
After taking a look at cocogitto issues I noticed the git-hooks was a recent addition, bumping the cocogitto dependency in koji fixed the issue.

**Comment by its-danny** [comment]
thanks for investigating this! will release a new version with updated cocogitto in a few minutes.
