### ISSUE TITLE
Cannot enter the hash character `#`

### ISSUE THREAD

**Issue by lucatrv** [cococonscious/koji#89]
**Describe the bug**
The hash character `#` cannot be entered.

**To Reproduce**
Run `koji` and try to enter the hash character `#`, either directly by typing or by copy/paste.

**Additional context**
I'm on Windows 10, I tried both with Git Bash and Powershell.

**Comment by cococonscious** [comment]
While I couldn't reproduce the bug on my Windows machine, could you please try again with the main branch head (`cargo install --git https://github.com/cococonscious/koji`) and see if it's working now? Maybe the new prompt library handles it differently...

**Comment by lucatrv** [comment]
I confirm that the issue is still present in the current released version 2.2.0, but it is not present in the main branch head. So apparently the issue has already been fixed with some recent commit yet to be released.
