### ISSUE TITLE
Needs Clarification: Why and When was this Repo transferred?

### ISSUE THREAD

**Issue by coolaj86** [cococonscious/koji#97]
In the wake of the xz / Jia Tan situation, I'm much more cautious about ownership changes and such.

I can confirm via https://web.archive.org/web/20240911185322/https://github.com/its-danny that the original author @its-danny seems to have transferred this repo.

<img width="1192" alt="Screenshot 2024-09-11 at 12 56 19 PM" src="https://github.com/user-attachments/assets/4a997806-a583-4303-a465-cb2683de30b3">

However, can we know why this repo was transferred? Was there any Issue with discussion about it? (I couldn't find one)

How do we know that @cococonscious <https://web.archive.org/web/20240911185918/https://github.com/cococonscious> is a trustworthy, good actor? This seems to be an account that was _just_ created. Perhaps a new pseudonym for a previous contributor who wishes to remain more anonymous than before? It doesn't mean anything necessarily, but it is a red flag to consider.

To be clear: I'm _not_ making any judgements or accusations. I have no reason to be suspicious. I'm just pointing out obvious and public things and asking for clarity on the change because I'm a maintainer of Webi and I have to do my own due diligence to feel positive about a seemingly-abrupt change in project leadership and possible downstream consequences.

**Comment by cococonscious** [comment]
Hi AJ, thanks for being cautious.
While I can't answer as to what Danny's personal reasons are exactly, you can find how the transfer was initiated in this comment on an issue: https://github.com/cococonscious/koji/issues/91#issuecomment-2323415310
Regarding my own trustworthiness: You cannot _know_ that anyone on the internet is trustworthy, you can simply make educated guesses. To help with that: By simply going through my account activity you can see that it is **not** a new account, but that it's in fact over 3 years old (https://github.com/cococonscious?tab=overview&from=2021-09-01&to=2021-09-30). My account is linked to my real-life identity, which you can see by me using my actual full name and linking both my company, my LinkedIn profile, and the in-person competitions I participated in. I honestly don't know what would increase my trustworthiness any further.

Is there anything else you want to know?

**Comment by coolaj86** [comment]
Thanks @cococonscious,

Seeing 2 following / 2 followers / 4 repos is what made me think it's a new account, but I see the history in the contributions map now. In the age of Ai and with the number of bots I have to deal with, I don't trust anything I see anymore in regards to profile pictures, bios, etc. I assume everything is fake by default. 🙃

Seeing the convo between you and @its-danny (and this bit of convo between us) satisfies my concern. I'll bring in your PR to Webi shortly.
